version: "3"

secrets:
  webpassword:
    external: true

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    secrets:
      - webpassword
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      VIRTUAL_HOST: 'pihole.serverpi4.local'
      TZ: 'Europe/Busingen'
      WEBPASSWORD: '/run/secrets/webpassword'
      FTLCONF_REPLY_ADDR4: '192.168.178.27'
      ADMIN_EMAIL: 'pihole@englerts.de'
      # Uncensored DNS provided by Digital Courage and OpenNIC 
      PIHOLE_DNS: '5.9.164.112;195.10.195.195 '
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped